=== liar1974/Database/HW3/hotel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="hotels">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="hotel" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="hotel_chain" type="xs:string"/>
							<xs:element name="hotel_branch_name" type="xs:string"/>
							<xs:element name="latitude" type="xs:double"/>
							<xs:element name="longitude" type="xs:double"/>
							<xs:element name="capacity" type="xs:int"/>
							<xs:element name="address">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="street_no" type="xs:int"/>
										<xs:element name="street_name" type="xs:string"/>
										<xs:element name="city" type="xs:string"/>
										<xs:element name="state" type="xs:string"/>
										<xs:element name="zip" type="xs:int"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="hotel_pk">
			<xs:selector xpath=".//hotel"/>
			<xs:field xpath="hotel_chain"/>
			<xs:field xpath="hotel_branch_name"/>
		</xs:key>
	</xs:element>
</xs:schema>

=== liar1974/Database/HW3/hotel.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hotel.xsl"?>
<hotels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hotel.xsd">
	<hotel>
		<hotel_chain>Hilton</hotel_chain>
		<hotel_branch_name>B1</hotel_branch_name>
		<latitude>47.6062095</latitude>
		<longitude>-122.3078</longitude>
		<capacity>300</capacity>
		<address>
			<street_no>406</street_no>
			<street_name>Washington</street_name>
			<city>Seattle</city>
			<state>WA</state>
			<zip>98104</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Doubletree</hotel_chain>
		<hotel_branch_name>B2</hotel_branch_name>
		<latitude>14.020137</latitude>
		<longitude>-118.29</longitude>
		<capacity>900</capacity>
		<address>
			<street_no>132</street_no>
			<street_name>Main</street_name>
			<city>Los Angeles</city>
			<state>CA</state>
			<zip>90007</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Hilton</hotel_chain>
		<hotel_branch_name>B3</hotel_branch_name>
		<latitude>37.3297849</latitude>
		<longitude>-121.8996</longitude>
		<capacity>100</capacity>
		<address>
			<street_no>300</street_no>
			<street_name>Almaden Boulevard</street_name>
			<city>San Jose</city>
			<state>CA</state>
			<zip>95110</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Hyatt</hotel_chain>
		<hotel_branch_name>B4</hotel_branch_name>
		<latitude>14.026535</latitude>
		<longitude>-118.265</longitude>
		<capacity>500</capacity>
		<address>
			<street_no>148</street_no>
			<street_name>Exposition</street_name>
			<city>Los Angeles</city>
			<state>CA</state>
			<zip>90007</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Hilton</hotel_chain>
		<hotel_branch_name>B5</hotel_branch_name>
		<latitude>30.120635</latitude>
		<longitude>-70.27</longitude>
		<capacity>150</capacity>
		<address>
			<street_no>678</street_no>
			<street_name>East Monroe Street</street_name>
			<city>Chicago</city>
			<state>IL</state>
			<zip>60603</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Doublestree</hotel_chain>
		<hotel_branch_name>B6</hotel_branch_name>
		<latitude>34.024547</latitude>
		<longitude>-118.288</longitude>
		<capacity>140</capacity>
		<address>
			<street_no>910</street_no>
			<street_name>Hoover</street_name>
			<city>Los Angeles</city>
			<state>CA</state>
			<zip>90007</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Doubletree</hotel_chain>
		<hotel_branch_name>B7</hotel_branch_name>
		<latitude>40.7142691</latitude>
		<longitude>-74.239</longitude>
		<capacity>600</capacity>
		<address>
			<street_no>160</street_no>
			<street_name>Main</street_name>
			<city>New York</city>
			<state>NY</state>
			<zip>11209</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Doubletree</hotel_chain>
		<hotel_branch_name>B8</hotel_branch_name>
		<latitude>35.055635</latitude>
		<longitude>-120.30</longitude>
		<capacity>1300</capacity>
		<address>
			<street_no>2050</street_no>
			<street_name>Gateway Place</street_name>
			<city>San Jose</city>
			<state>CA</state>
			<zip>95110</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Caesars</hotel_chain>
		<hotel_branch_name>B9</hotel_branch_name>
		<latitude>44.026535</latitude>
		<longitude>-121.265</longitude>
		<capacity>900</capacity>
		<address>
			<street_no>797</street_no>
			<street_name>California</street_name>
			<city>Portland</city>
			<state>OR</state>
			<zip>97405</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Caesars</hotel_chain>
		<hotel_branch_name>B10</hotel_branch_name>
		<latitude>46.120635</latitude>
		<longitude>-122.6008</longitude>
		<capacity>500</capacity>
		<address>
			<street_no>314</street_no>
			<street_name>3rd</street_name>
			<city>Seattle</city>
			<state>WA</state>
			<zip>98104</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Ario</hotel_chain>
		<hotel_branch_name>B11</hotel_branch_name>
		<latitude>40.7142691</latitude>
		<longitude>-74.8288</longitude>
		<capacity>130</capacity>
		<address>
			<street_no>649</street_no>
			<street_name>3rd</street_name>
			<city>New Yord</city>
			<state>NY</state>
			<zip>11209</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Ario</hotel_chain>
		<hotel_branch_name>B12</hotel_branch_name>
		<latitude>44.020137</latitude>
		<longitude>-76.29</longitude>
		<capacity>200</capacity>
		<address>
			<street_no>863</street_no>
			<street_name>Main</street_name>
			<city>Seattle</city>
			<state>WA</state>
			<zip>98104</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Carlton</hotel_chain>
		<hotel_branch_name>B13</hotel_branch_name>
		<latitude>34.055635</latitude>
		<longitude>-110.30</longitude>
		<capacity>120</capacity>
		<address>
			<street_no>991</street_no>
			<street_name>Vermont</street_name>
			<city>Los Angeles</city>
			<state>CA</state>
			<zip>90007</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Carlton</hotel_chain>
		<hotel_branch_name>B14</hotel_branch_name>
		<latitude>37.026535</latitude>
		<longitude>-120.265</longitude>
		<capacity>100</capacity>
		<address>
			<street_no>282</street_no>
			<street_name>Magnolia</street_name>
			<city>San Jose</city>
			<state>CA</state>
			<zip>94086</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Marriott</hotel_chain>
		<hotel_branch_name>B15</hotel_branch_name>
		<latitude>17.120635</latitude>
		<longitude>-116.27</longitude>
		<capacity>300</capacity>
		<address>
			<street_no>504</street_no>
			<street_name>Adams</street_name>
			<city>Los Angeles</city>
			<state>CA</state>
			<zip>90089</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Marriott</hotel_chain>
		<hotel_branch_name>B16</hotel_branch_name>
		<latitude>40.542691</latitude>
		<longitude>-76.28</longitude>
		<capacity>700</capacity>
		<address>
			<street_no>660</street_no>
			<street_name>Main</street_name>
			<city>New York</city>
			<state>NY</state>
			<zip>11209</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Hilton</hotel_chain>
		<hotel_branch_name>B17</hotel_branch_name>
		<latitude>40.7142691</latitude>
		<longitude>-73.29</longitude>
		<capacity>500</capacity>
		<address>
			<street_no>755</street_no>
			<street_name>Rose</street_name>
			<city>New York</city>
			<state>NY</state>
			<zip>11209</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Hyatt</hotel_chain>
		<hotel_branch_name>B18</hotel_branch_name>
		<latitude>41.7142691</latitude>
		<longitude>-73.30</longitude>
		<capacity>900</capacity>
		<address>
			<street_no>998</street_no>
			<street_name>Magnolia</street_name>
			<city>New York</city>
			<state>NY</state>
			<zip>11209</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Westin</hotel_chain>
		<hotel_branch_name>B19</hotel_branch_name>
		<latitude>40.142691</latitude>
		<longitude>-74.265</longitude>
		<capacity>900</capacity>
		<address>
			<street_no>412</street_no>
			<street_name>Main</street_name>
			<city>New York</city>
			<state>NY</state>
			<zip>11209</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Best Western</hotel_chain>
		<hotel_branch_name>B20</hotel_branch_name>
		<latitude>45.120635</latitude>
		<longitude>-122.27</longitude>
		<capacity>400</capacity>
		<address>
			<street_no>819</street_no>
			<street_name>Washington</street_name>
			<city>Portland</city>
			<state>OR</state>
			<zip>97405</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Doubletree</hotel_chain>
		<hotel_branch_name>B21</hotel_branch_name>
		<latitude>30.024547</latitude>
		<longitude>-122.288</longitude>
		<capacity>80</capacity>
		<address>
			<street_no>595</street_no>
			<street_name>Magnolia</street_name>
			<city>Portland</city>
			<state>OR</state>
			<zip>97405</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Hilton</hotel_chain>
		<hotel_branch_name>B22</hotel_branch_name>
		<latitude>64.020137</latitude>
		<longitude>-108.29</longitude>
		<capacity>110</capacity>
		<address>
			<street_no>349</street_no>
			<street_name>Magnolia</street_name>
			<city>San Francisco</city>
			<state>CA</state>
			<zip>94086</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Hilton</hotel_chain>
		<hotel_branch_name>B23</hotel_branch_name>
		<latitude>45.5234515</latitude>
		<longitude>-121.30</longitude>
		<capacity>800</capacity>
		<address>
			<street_no>252</street_no>
			<street_name>Rose</street_name>
			<city>Portland</city>
			<state>OR</state>
			<zip>97405</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Holidays Inn</hotel_chain>
		<hotel_branch_name>B24</hotel_branch_name>
		<latitude>34.024547</latitude>
		<longitude>-117.288</longitude>
		<capacity>150</capacity>
		<address>
			<street_no>980</street_no>
			<street_name>Washington</street_name>
			<city>Los Angeles</city>
			<state>CA</state>
			<zip>90007</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Holidays Inn</hotel_chain>
		<hotel_branch_name>B25</hotel_branch_name>
		<latitude>40.691</latitude>
		<longitude>-73.29</longitude>
		<capacity>40</capacity>
		<address>
			<street_no>503</street_no>
			<street_name>Magnolia</street_name>
			<city>New York</city>
			<state>NY</state>
			<zip>11209</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Westbound</hotel_chain>
		<hotel_branch_name>B26</hotel_branch_name>
		<latitude>40.2691</latitude>
		<longitude>-74.09729</longitude>
		<capacity>100</capacity>
		<address>
			<street_no>532</street_no>
			<street_name>Ocean</street_name>
			<city>New York</city>
			<state>NY</state>
			<zip>11209</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Westin</hotel_chain>
		<hotel_branch_name>B27</hotel_branch_name>
		<latitude>47.362095</latitude>
		<longitude>-122.5708</longitude>
		<capacity>80</capacity>
		<address>
			<street_no>134</street_no>
			<street_name>Main</street_name>
			<city>Seattle</city>
			<state>WA</state>
			<zip>98104</zip>
		</address>
	</hotel>
	<hotel>
		<hotel_chain>Best Western</hotel_chain>
		<hotel_branch_name>B28</hotel_branch_name>
		<latitude>34.120635</latitude>
		<longitude>-118.27</longitude>
		<capacity>130</capacity>
		<address>
