=== liar1974/Database/HW3/participation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="SSNTypeParticipation">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{3}-\d{2}-\d{4}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="participationInfo">
	    <xs:complexType>
	        <xs:sequence>
	            <xs:element name="individualParticipation" maxOccurs="unbounded">
	                <xs:complexType>
	                    <xs:sequence>
	                        <xs:element name="studentSSN" minOccurs="1" maxOccurs="1" type="SSNTypeParticipation"/>
	                        <xs:element name="conferenceName" minOccurs="1" maxOccurs="1" type="xs:string"/>
	                        <xs:element name="conferenceYear" minOccurs="1" maxOccurs="1" type="xs:int"/>
	                        <xs:element name="registrationNo" minOccurs="1" maxOccurs="1" type="xs:string"/>
	                        <xs:element name="registrationFee" minOccurs="0" maxOccurs="1" type="xs:int"/>
	                    </xs:sequence>
	                </xs:complexType>
	            </xs:element>
	        </xs:sequence>
	    </xs:complexType>
	</xs:element>
</xs:schema>

=== liar1974/Database/HW3/participation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="participation.xsl"?>
<participationInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="participation.xsd">
	<individualParticipation>
		<studentSSN>622-12-5748</studentSSN>
		<conferenceName>ACL</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>2010100</registrationNo>
		<registrationFee>100</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>622-12-5748</studentSSN>
		<conferenceName>ACL</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>2011890</registrationNo>
		<registrationFee>120</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>622-12-5748</studentSSN>
		<conferenceName>ACM Sigdial</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>S9769</registrationNo>
		<registrationFee>170</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>630-44-3532</studentSSN>
		<conferenceName>CVPR</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>P0000001</registrationNo>
		<registrationFee>400</registrationFee>
	</individualParticipation>
    <individualParticipation>
	<studentSSN>630-44-3532</studentSSN>
	    <conferenceName>CVPR</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>P0000005</registrationNo>
		<registrationFee>400</registrationFee>
	</individualParticipation>
    <individualParticipation>
		<studentSSN>623-62-7824</studentSSN>
		<conferenceName>VLDB</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>VL5742</registrationNo>
		<registrationFee>300</registrationFee>
	</individualParticipation>
    <individualParticipation>
		<studentSSN>613-84-8679</studentSSN>
		<conferenceName>ACM Siggraph</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>SIG009</registrationNo>
		<registrationFee>600</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>625-88-5088</studentSSN>
		<conferenceName>ACM Sigdial</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>S7976</registrationNo>
		<registrationFee>270</registrationFee>
	</individualParticipation>
    <individualParticipation>
		<studentSSN>625-42-8940</studentSSN>
		<conferenceName>ACL</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>2010</registrationNo>
		<registrationFee>100</registrationFee>
	</individualParticipation>
    <individualParticipation>
		<studentSSN>625-42-8940</studentSSN>
		<conferenceName>ACM Sigir</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>124</registrationNo>
		<registrationFee>200</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>628-58-8156</studentSSN>
		<conferenceName>ACM Siggraph</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>SIG0089</registrationNo>
		<registrationFee>600</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>627-48-8192</studentSSN>
		<conferenceName>VLDB</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>VL1841</registrationNo>
		<registrationFee>300</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>624-40-5028</studentSSN>
		<conferenceName>ACL</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>2010</registrationNo>
		<registrationFee>100</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>616-55-3688</studentSSN>
		<conferenceName>CVPR</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>P0000008</registrationNo>
		<registrationFee>400</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>616-55-3688</studentSSN>
		<conferenceName>ACM Sigdial</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>S9080</registrationNo>
		<registrationFee>190</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>620-16-0198</studentSSN>
		<conferenceName>ACM Sigir</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>194</registrationNo>
		<registrationFee>200</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>622-93-3200</studentSSN>
		<conferenceName>ACL</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>20118734</registrationNo>
		<registrationFee>120</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>612-58-6604</studentSSN>
		<conferenceName>ECCV</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>1</registrationNo>
		<registrationFee>200</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>613-45-9153</studentSSN>
		<conferenceName>ACM Sigir</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>198</registrationNo>
		<registrationFee>200</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>613-45-9153</studentSSN>
		<conferenceName>ACM Siggraph</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>SIG006</registrationNo>
		<registrationFee>700</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>630-09-3217</studentSSN>
		<conferenceName>ACM Siggraph</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>SIG004</registrationNo>
		<registrationFee>700</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>616-18-5901</studentSSN>
		<conferenceName>ECCV</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>2</registrationNo>
		<registrationFee>200</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>628-67-3227</studentSSN>
		<conferenceName>VLDB</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>VL8770</registrationNo>
		<registrationFee>300</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>622-66-5110</studentSSN>
		<conferenceName>VLDB</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>VL9070</registrationNo>
		<registrationFee>330</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>615-07-7886</studentSSN>
		<conferenceName>ACM Sigdial</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>S9070</registrationNo>
		<registrationFee>250</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>615-07-7886</studentSSN>
		<conferenceName>ACL</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>2010231</registrationNo>
		<registrationFee>100</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>615-07-7886</studentSSN>
		<conferenceName>ACL</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>2011342</registrationNo>
		<registrationFee>120</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>615-07-7886</studentSSN>
		<conferenceName>ACM Sigdial</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>1000001</registrationNo>
		<registrationFee>200</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>628-42-4276</studentSSN>
		<conferenceName>ACL</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>20105234</registrationNo>
		<registrationFee>100</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>615-38-0956</studentSSN>
		<conferenceName>ECCV</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>3</registrationNo>
		<registrationFee>200</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>617-27-3364</studentSSN>
		<conferenceName>VLDB</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>VL1740</registrationNo>
		<registrationFee>300</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>612-05-8786</studentSSN>
		<conferenceName>ACM Sigir</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>187</registrationNo>
		<registrationFee>200</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>612-05-8786</studentSSN>
		<conferenceName>CVPR</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>P000098</registrationNo>
		<registrationFee>400</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>620-06-4581</studentSSN>
		<conferenceName>ACL</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>2010324</registrationNo>
		<registrationFee>100</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>617-71-1016</studentSSN>
		<conferenceName>ACM Siggraph</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>SIG002</registrationNo>
		<registrationFee>700</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>617-71-1016</studentSSN>
		<conferenceName>VLDB</conferenceName>
		<conferenceYear>2011</conferenceYear>
		<registrationNo>VL1740</registrationNo>
		<registrationFee>330</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>617-71-1016</studentSSN>
		<conferenceName>VLDB</conferenceName>
		<conferenceYear>2010</conferenceYear>
		<registrationNo>VL1000</registrationNo>
		<registrationFee>300</registrationFee>
	</individualParticipation>
	<individualParticipation>
		<studentSSN>623-53-0255</studentSSN>
		<conferenceName>CVPR</conferenceName>
		<conferenceYear>2010</conferenceYear>
