=== liar1974/Database/HW3/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:simpleType name="SSNType">
		<xs:restriction base="xs:string">
		    <xs:pattern value="\d{3}-\d{2}-\d{4}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="students">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="student" minOccurs="1" maxOccurs="unbounded">
				    <xs:complexType>
				        <xs:sequence>
				            <xs:element name="SSN" minOccurs="1" maxOccurs="1" type="SSNType"/>
				            <xs:element name="student_name" minOccurs="1" maxOccurs="1">
				                <xs:complexType>
				                    <xs:sequence>
				                        <xs:element name="first_name" minOccurs="1" maxOccurs="1" type="xs:string"/>
				                        <xs:element name="last_name" minOccurs="1" maxOccurs="1" type="xs:string"/>
				                    </xs:sequence>
				                </xs:complexType>
				            </xs:element>
				            <xs:element name="age" minOccurs="0" maxOccurs="1" type="xs:int"/>
				            <xs:element name="institutionName" minOccurs="1" maxOccurs="1" type="xs:string"/>
				            <xs:element name="email" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
				        </xs:sequence>
				    </xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="student_SSN_pk">
			<xs:selector xpath=".//student"/>
			<xs:field xpath="SSN"/>
		</xs:key>
	</xs:element>
</xs:schema>

=== liar1974/Database/HW3/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="student.xsl"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student.xsd">
	<student>
		<SSN>622-12-5748</SSN>
		<student_name>
			<first_name>Alexander</first_name>
			<last_name>Mart</last_name>
		</student_name>
		<age>26</age>
		<institutionName>UCSF</institutionName>
		<email>Alexander@yahoo.com</email>
	</student>
	<student>
		<SSN>630-44-3532</SSN>
		<student_name>
			<first_name>Ali</first_name>
			<last_name>Daria</last_name>
		</student_name>
		<age>42</age>
		<institutionName>UC Berkeley</institutionName>
		<email>Ali@yahoo.com</email>
		<email>Ali@hotmail.com</email>
	</student>
	<student>
		<SSN>618-58-4662</SSN>
		<student_name>
			<first_name>Amir</first_name>
			<last_name>Tark</last_name>
		</student_name>
		<age>18</age>
		<institutionName>Stanford</institutionName>
		<email>Amir@yahoo.com</email>
	</student>
	<student>
		<SSN>623-62-7824</SSN>
		<student_name>
			<first_name>Antonio</first_name>
			<last_name>Milsh</last_name>
		</student_name>
		<age>34</age>
		<institutionName>MIT</institutionName>
		<email>Antonio@yahoo.com</email>
	</student>
	<student>
		<SSN>613-84-8679</SSN>
		<student_name>
			<first_name>Ashish</first_name>
			<last_name>Moore</last_name>
		</student_name>
		<age>20</age>
		<institutionName>Caltech</institutionName>
		<email>Ashish@yahoo.com</email>
	</student>
	<student>
		<SSN>625-88-5088</SSN>
		<student_name>
			<first_name>Benjamin</first_name>
			<last_name>Timber</last_name>
		</student_name>
		<age>23</age>
		<institutionName>Iowa</institutionName>
		<email>Benjamin@yahoo.com</email>
		<email>benjamin@gmail.com</email>
	</student>
	<student>
		<SSN>625-42-8940</SSN>
		<student_name>
			<first_name>Bob</first_name>
			<last_name>Shruder</last_name>
		</student_name>
		<age>46</age>
		<institutionName>USC</institutionName>
		<email>Bob@hotmail.com</email>
	</student>
	<student>
		<SSN>628-58-8156</SSN>
		<student_name>
			<first_name>Carlos</first_name>
			<last_name>Gomez</last_name>
		</student_name>
		<age>53</age>
		<institutionName>USC</institutionName>
		<email>Carlos@yahoo.com</email>
	</student>
	<student>
		<SSN>627-48-8192</SSN>
		<student_name>
			<first_name>David</first_name>
			<last_name>Deber</last_name>
		</student_name>
		<age>39</age>
		<institutionName>UCLA</institutionName>
		<email>David@yahoo.com</email>
		<email>David@hotmail.com</email>
	</student>
	<student>
		<SSN>624-40-5028</SSN>
		<student_name>
			<first_name>Dimitris</first_name>
			<last_name>Harel</last_name>
		</student_name>
		<age>46</age>
		<institutionName>Google</institutionName>
		<email>Dimitris@hotmail.com</email>
	</student>
	<student>
		<SSN>616-55-3688</SSN>
		<student_name>
			<first_name>Fernando</first_name>
			<last_name>Alexander</last_name>
		</student_name>
		<age>48</age>
		<institutionName>Google</institutionName>
		<email>Fernando@yahoo.com</email>
	</student>
	<student>
		<SSN>620-16-0198</SSN>
		<student_name>
			<first_name>Goran</first_name>
			<last_name>Alav</last_name>
		</student_name>
		<age>42</age>
		<institutionName>Texas A&amp;M</institutionName>
		<email>Goran@yahoo.com</email>
	</student>
	<student>
		<SSN>622-93-3200</SSN>
		<student_name>
			<first_name>Hans</first_name>
			<last_name>Amiri</last_name>
		</student_name>
		<age>36</age>
		<institutionName>AT&amp;T labs</institutionName>
		<email>Hans@yahoo.com</email>
	</student>
	<student>
		<SSN>612-58-6604</SSN>
		<student_name>
			<first_name>Harry</first_name>
			<last_name>Antonio</last_name>
		</student_name>
		<age>23</age>
		<institutionName>Bell labs</institutionName>
		<email>Harry@yahoo.com</email>
	</student>
	<student>
		<SSN>613-45-9153</SSN>
		<student_name>
			<first_name>Henrik</first_name>
			<last_name>Ashish</last_name>
		</student_name>
		<age>27</age>
		<institutionName>UCSF</institutionName>
		<email>Henrik@yahoo.com</email>
	</student>
	<student>
		<SSN>630-09-3217</SSN>
		<student_name>
			<first_name>Ivan</first_name>
			<last_name>Benjamin</last_name>
		</student_name>
		<age>51</age>
		<institutionName>USC</institutionName>
		<email>Ivan@yahoo.com</email>
	</student>	
	<student>
		<SSN>616-18-5901</SSN>
		<student_name>
			<first_name>Jack</first_name>
			<last_name>Neuman</last_name>
		</student_name>
		<age>28</age>
		<institutionName>MIT</institutionName>
		<email>Jack@yahoo.com</email>
		<email>Jack@hotmail.com</email>
		<email>Jack@gmail.com</email>
		<email>Jack@aol.com</email>
	</student>		
	<student>
		<SSN>628-67-3227</SSN>
		<student_name>
			<first_name>Jason</first_name>
			<last_name>Koch</last_name>
		</student_name>
		<age>40</age>
		<institutionName>MIT</institutionName>
		<email>Jason@yahoo.com</email>
		<email>Jason@hotmail.com</email>
	</student>		
	<student>
		<SSN>622-66-5110</SSN>
		<student_name>
			<first_name>John</first_name>
			<last_name>Shin</last_name>
		</student_name>
		<age>51</age>
		<institutionName>Harvard</institutionName>
		<email>John@yahoo.com</email>
		<email>John@hotmail.com</email>
	</student>		
	<student>
		<SSN>615-07-7886</SSN>
		<student_name>
			<first_name>Jose</first_name>
			<last_name>Barnes</last_name>
		</student_name>
		<age>28</age>
		<institutionName>Harvard</institutionName>
		<email>Jose@yahoo.com</email>
		<email>Jose@hotmail.com</email>
	</student>
	<student>
		<SSN>628-42-4276</SSN>
		<student_name>
			<first_name>Juan</first_name>
			<last_name>Lopez</last_name>
		</student_name>
		<age>50</age>
		<institutionName>Delaware</institutionName>
		<email>Juan@yahoo.com</email>
	</student>
	<student>
		<SSN>615-38-0956</SSN>
		<student_name>
			<first_name>Kun</first_name>
			<last_name>Gassr</last_name>
		</student_name>
		<age>35</age>
		<institutionName>Minessota</institutionName>
		<email>Kun@yahoo.com</email>
		<email>Kun@hotmail.com</email>
	</student>	
	<student>
		<SSN>617-27-3364</SSN>
		<student_name>
			<first_name>Lee</first_name>
			<last_name>Liew</last_name>
		</student_name>
		<age>48</age>
		<institutionName>UMD</institutionName>
		<email>Lee@yahoo.com</email>
	</student>
	<student>
		<SSN>612-05-8786</SSN>
		<student_name>
			<first_name>Luis</first_name>
			<last_name>Smith</last_name>
		</student_name>
		<age>22</age>
		<institutionName>UCSB</institutionName>
		<email>Luis@yahoo.com</email>
		<email>Luis@hotmail.com</email>
		<email>Luis@gmail.com</email>
		<email>Luis@aol.com</email>
	</student>
	<student>
		<SSN>620-06-4581</SSN>
		<student_name>
			<first_name>Marcus</first_name>
			<last_name>Stacker</last_name>
		</student_name>
		<age>39</age>
		<institutionName>ICT</institutionName>
		<email>Marcus@yahoo.com</email>
	</student>
	<student>
		<SSN>617-71-1016</SSN>
		<student_name>
			<first_name>Maria</first_name>
			<last_name>Ghosh</last_name>
		</student_name>
		<age>49</age>
		<institutionName>ISI</institutionName>
		<email>Maria@yahoo.com</email>
	</student>
	<student>
		<SSN>623-53-0255</SSN>
		<student_name>
			<first_name>Mark</first_name>
			<last_name>Marr</last_name>
		</student_name>
		<age>36</age>
		<institutionName>CMU</institutionName>
		<email>Mark@yahoo.com</email>
		<email>Mark@hotmail.com</email>
	</student>
	<student>
		<SSN>618-54-6905</SSN>
		<student_name>
			<first_name>Micheal</first_name>
			<last_name>Davidson</last_name>
		</student_name>
		<age>32</age>
		<institutionName>Delft</institutionName>
		<email>Micheal@hotmail.com</email>
	</student>
</students>
